### ISSUE TITLE
Xfce4 Panel issue

### ISSUE THREAD

**Issue by syndrizzle** [rasatpc/Xfce-FvwmEXT#3]
Hello! I am having some problem when using xfce4-panel with fvwm, although I am not using your extensions, nor I am using the xfce de with fvwm, the problem is I have to click multiple times on the applications window list, or any dock plugin, to minimize the application, if it is minimized it gets maximized in one click, the issue is only with minimizing...
Also I am having some problem where if I were to use the global app menu, like https://github.com/rilian-la-te/vala-panel-appmenu, it doesnt follow it correctly and if i click on the panel the global menu disappears, tho this works fine on a standalone xfce session :(
I have added this `Style Xfce4-panel !Title, !Borders, !Handles, Sticky, StaysOnBottom, NoHandles, EWMHIgnoreStrutHints, EWMHPlacementIgnoreWorkingArea, WindowListSkip, PositionPlacement 0 -0, NeverFocus` to my config file of fvwm, I dont know if I have to add something else, but if you can help me with this, it would be amazing!

**Comment by rasatpc** [comment]
Does the minimize work when running Xfce alone? If it does, try my Thumbnail extension and modify it as you like.
